tags:
  - name: Testing
    description: API for clearing the database

paths:
  /hometask/api/testing/all-data:
    delete:
      summary: "Clear database: delete all data from all tables/collections"
      tags: [ Testing ]
      responses:
        204:
          description: All data deleted
